// Writes out/sw.js after next build. The precache list cannot be hand-written
// because Next content-hashes its filenames, and the build id has to change on
// every deploy or no browser ever notices a new worker.
import { readdirSync, statSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { createHash } from 'node:crypto';

const OUT = 'out';

// The big binaries are already kept in Cache Storage by src/lib/assets.ts and
// are fetched on demand. Precaching them would download ~26MB up front and
// store a second copy.
const SKIP = [/^\/ort\//, /^\/qpdf\//, /^\/models\//, /\.wasm$/, /^\/sw\.js$/];

function walk(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, acc);
    else acc.push('/' + relative(OUT, full).split('\\').join('/'));
  }
  return acc;
}

const files = walk(OUT)
  .filter((p) => !SKIP.some((re) => re.test(p)))
  // index.html is served at the directory URL, which is what a navigation asks for
  .map((p) => (p.endsWith('/index.html') ? p.slice(0, -'index.html'.length) : p))
  .sort();

const hash = createHash('sha256');
for (const p of files) hash.update(p);
hash.update(readFileSync(join(OUT, 'index.html')));
const BUILD_ID = hash.digest('hex').slice(0, 12);

// Kept in step with the redirects in vercel.json, which do not exist offline.
const REDIRECTS = {
  '/tools/csv-cleaner/': '/tools/spreadsheet-tools/',
  '/tools/image-compressor/': '/tools/image-tools/',
  '/tools/background-remover/': '/tools/image-tools/',
  '/tools/passport-photo/': '/tools/image-tools/',
  '/tools/json-csv-yaml-converter/': '/tools/developer-tools/',
  '/tools/markdown-converter/': '/tools/developer-tools/',
  '/tools/text-utilities/': '/tools/developer-tools/',
};

const sw = `// Generated by scripts/build-sw.mjs. Do not edit.
const BUILD = ${JSON.stringify(BUILD_ID)};
const CACHE = 'fsk-shell-' + BUILD;
const PREFIX = 'fsk-shell-';
const SHELL = ${JSON.stringify(files)};
const REDIRECTS = ${JSON.stringify(REDIRECTS)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      // Only our own shell caches. assets.ts owns its own and must survive.
      for (const name of await caches.keys()) {
        if (name.startsWith(PREFIX) && name !== CACHE) await caches.delete(name);
      }
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});

function shellUrl(url) {
  let path = url.pathname;
  if (REDIRECTS[path]) path = REDIRECTS[path];
  else if (REDIRECTS[path + '/']) path = REDIRECTS[path + '/'];
  // trailingSlash: true, so /tools/x and /tools/x/ are the same page
  if (!path.endsWith('/') && !path.includes('.')) path += '/';
  return path;
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    (async () => {
      // No cache name, so this also finds whatever assets.ts stored. That is
      // what keeps the models and wasm from being downloaded a second time.
      const hit = await caches.match(request, { ignoreSearch: true });
      if (hit) return hit;

      if (request.mode === 'navigate') {
        const shell = await caches.match(shellUrl(url), { ignoreSearch: true });
        if (shell) return shell;
      }

      try {
        return await fetch(request);
      } catch {
        const offline = await caches.match('/404.html');
        if (offline) return offline;
        return new Response('Offline', { status: 503, statusText: 'Offline' });
      }
    })(),
  );
});
`;

writeFileSync(join(OUT, 'sw.js'), sw, 'utf8');

const bytes = files.reduce((n, p) => {
  const file = p.endsWith('/') ? join(OUT, p, 'index.html') : join(OUT, p);
  try {
    return n + statSync(file).size;
  } catch {
    return n;
  }
}, 0);

console.log(
  `sw.js: build ${BUILD_ID}, ${files.length} files precached, ${(bytes / 1048576).toFixed(2)} MiB`,
);
