/**
 * The document a first-time visitor lands on. It doubles as a short reference
 * for the Markdown this editor supports, so it is worth keeping rather than
 * being noise to delete — and it exercises headings, a table, a fenced code
 * block, lists, task lists and a blockquote, which is exactly what the theme
 * picker needs in order to show a real difference.
 *
 * Written as an array of lines so the fenced code blocks below do not need
 * backtick gymnastics inside a template literal.
 */
export const SAMPLE_DOCUMENT: string = [
  '# Markdown, at a glance',
  '',
  'This editor renders as you type and never sends a byte anywhere. Write on the',
  'left, read on the right, then export a standalone HTML file or print to PDF.',
  '',
  '> **Everything stays on this device.** The Markdown you paste here is parsed,',
  '> highlighted and exported by your own browser — there is no server involved.',
  '',
  '## The basics',
  '',
  '- **bold**, *italic*, ~~struck through~~ and `inline code`',
  '- A [link](https://example.com), or a bare URL like https://example.com',
  '- Nested lists:',
  '  1. First',
  '  2. Second',
  '     - and deeper still',
  '',
  '## Syntax reference',
  '',
  '| You write | You get | Notes |',
  '| --- | --- | --- |',
  '| `# Heading` | A level-1 heading | Up to six `#` |',
  '| `**bold**` | **bold** | `*italic*` for italics |',
  '| `> quoted` | A blockquote | Stacks with lists |',
  '| `---` | A horizontal rule | Three or more |',
  '| `![alt](url)` | An image | Local files work too |',
  '',
  '## Checklists',
  '',
  '- [x] Task lists render as real checkboxes',
  '- [x] Tables, strikethrough and autolinks are on',
  '- [ ] Pick a theme and export the result',
  '',
  '## Code blocks',
  '',
  'Add a language after the opening fence and it is highlighted:',
  '',
  '```ts',
  'type Doc = { title: string; words: number };',
  '',
  'function summarise(markdown: string): Doc {',
  '  const words = markdown.trim().split(/\\s+/).length;',
  '  return { title: markdown.split("\\n")[0], words };',
  '}',
  '```',
  '',
  '```bash',
  '# unknown languages fall back to plain text, never an error',
  'grep -c "hljs" export.html',
  '```',
  '',
  '---',
  '',
  '### Exporting',
  '',
  'Three ways out, all of them local:',
  '',
  '1. **Download .html** — one self-contained file, styles included.',
  '2. **Print / PDF** — opens your print dialog; choose *Save as PDF* for real,',
  '   selectable text rather than a picture of text.',
  '3. **Copy HTML** — the rendered markup, ready to paste elsewhere.',
  '',
  'Clear this document whenever you like; your draft is kept in this browser',
  'only, and the *Clear* button wipes it for good.',
  '',
].join('\n');
